### ISSUE TITLE
Issues with RBAC

### ISSUE THREAD

**Issue by falfaro** [juju-solutions/layer-calico#18]
On a Kubernetes cluster with RBAC enabled, deployed using Juju, Calico does not finish installation and blocks forever. I assume this is because Calico cannot access the API to retrieve Kubernetes extension.

In my particular case, these are the relevant bits from the Juju bundle I'm using to deploy Kubernetes:

```
  kubernetes-master:
    charm: cs:~containers/kubernetes-master-79
    num_units: 1
    options:
      authorization-mode: "RBAC,Node"
      channel: 1.9/stable
```

And:

```
  calico:
    charm: cs:~containers/calico-21
```  

I've found the following manifest which claims to allow Calico access to the Kubernetes API required for RBAC deployments: https://docs.projectcalico.org/v2.5/getting-started/kubernetes/installation/rbac.yaml (from https://docs.projectcalico.org/v2.5/getting-started/kubernetes/installation/integration)
